name: Dependency Submission

on:
  push:
    branches: [ 'main' ]

permissions:
  contents: write

jobs:
  dependency-submission:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v4
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 17
    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@v3
      env:
        STYTCH_PUBLIC_TOKEN: 'abc123'
        GOOGLE_OAUTH_CLIENT_ID: 'abc123'
        STYTCH_B2B_PUBLIC_TOKEN: 'abc123'
        STYTCH_B2B_ORG_ID: 'abc123'
        PASSKEYS_DOMAIN: 'abc123'
        STYTCH_UI_PUBLIC_TOKEN: 'abc123'
        UI_GOOGLE_CLIENT_ID: 'abc123'
